language: rust
rust:
  - nightly

before_script: |
  rustup component add rustfmt-preview
script: |
  cargo check --all-targets --verbose &&
  cargo fmt -- --check &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo
